/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#042419",
        "inverse-on-surface": "#f8f0de",
        "surface-variant": "#eae2d0",
        "on-tertiary-fixed-variant": "#8e130c",
        "on-tertiary": "#ffffff",
        "background": "#fff9ee",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-primary": "#ffffff",
        "on-surface-variant": "#414844",
        "outline": "#727974",
        "on-surface": "#1f1b11",
        "surface-container": "#f5eddb",
        "surface-container-high": "#efe8d6",
        "on-secondary-container": "#696456",
        "on-secondary-fixed": "#1f1b11",
        "surface": "#fff9ee",
        "on-primary-container": "#83a493",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#012115",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#410000",
        "on-error-container": "#93000a",
        "tertiary": "#480000",
        "surface-tint": "#456556",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#2e4d3f",
        "inverse-surface": "#343024",
        "on-error": "#ffffff",
        "primary-fixed": "#c7ebd8",
        "surface-dim": "#e1d9c8",
        "on-secondary-fixed-variant": "#4b473a",
        "secondary": "#635e50",
        "surface-container-highest": "#eae2d0",
        "secondary-fixed": "#eae2d0",
        "tertiary-container": "#700001",
        "primary-fixed-dim": "#accebc",
        "on-background": "#1f1b11",
        "secondary-container": "#eae2d0",
        "surface-bright": "#fff9ee",
        "on-tertiary-container": "#ff6f5d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cdc6b5",
        "surface-container-low": "#fbf3e1",
        "inverse-primary": "#accebc",
        "primary-container": "#1b3a2d",
        "outline-variant": "#c1c8c2",
        "tertiary-fixed": "#ffdad5"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
